#!/bin/bash
apt-get -y update
apt-get -y upgrade
mv /etc/hostname /etc/oldhostname
cp ./samba/hostname /etc/hostname
mv /etc/hosts /etc/oldhosts
cp ./samba/hosts /etc/hosts

apt-get -y install samba 
mkdir /srv/kozos
chmod 777 /srv/kozos
mkdir /srv/readonly
chmod 755 /srv/readonly

mv /etc/samba/smb.conf /etc/samba/oldsmb.conf
cp ./samba/smb.conf /etc/samba/smb.conf
service smbd restart
useradd user2 –c "user2" –g users –m –d /home/user2 –s /bin/bash
passwd user2
echo | 123
echo | 123
echo 
mkdir /srv/user2
chown user2 /srv/user2
chmod 700 /srv/user2
smbpasswd -a user2
service smbd restart
